-- TESTCASE 1 --
101 Ready

200 OK
testcase
200 OK
testcase
200 OK
200 Bye
-- TESTCASE 2 --
101 Ready
101 Ready
101 Ready
101 Ready
500 Busy
500 Busy
101 Ready
101 Ready
101 Ready
101 Ready
500 Busy
500 Busy
-- TESTCASE 3 --
101 Ready
Client timeout is disabled
200 OK
Client timeout is 1s
200 OK
492 Client timeout
-- TESTCASE 4 --
101 Ready
400 Too many arguments
200 Bye
-- TESTCASE 5 --
-- TESTCASE 6 --
101 Ready
testcase
200 OK
200 "parse" "This" "is" "a" "nice command!"
200 OK
590 Server shutdown
