cmdserv <info>: server ready for connections on port 12346
-- TESTCASE 1 --
cmdserv <info>: #1 connected from [::1]:10001
cmdserv <info>: #1 closing
-- TESTCASE 2 --
cmdserv <info>: #2 connected from [::1]:20011
cmdserv <info>: #3 connected from [::1]:20012
cmdserv <info>: #4 connected from [::1]:20013
cmdserv <info>: #5 connected from [::1]:20014
cmdserv <info>: #6 connected from [::1]:20015
cmdserv <warning>: too many connections, turning #6 away
cmdserv <info>: #6 closing
cmdserv <info>: #7 connected from [::1]:20016
cmdserv <warning>: too many connections, turning #7 away
cmdserv <info>: #7 closing
cmdserv <info>: #2 client disconnect
cmdserv <info>: #2 closing
cmdserv <info>: #3 client disconnect
cmdserv <info>: #3 closing
cmdserv <info>: #4 client disconnect
cmdserv <info>: #4 closing
cmdserv <info>: #5 client disconnect
cmdserv <info>: #5 closing
cmdserv <info>: #8 connected from [::1]:20021
cmdserv <info>: #9 connected from [::1]:20022
cmdserv <info>: #10 connected from [::1]:20023
cmdserv <info>: #11 connected from [::1]:20024
cmdserv <info>: #12 connected from [::1]:20025
cmdserv <warning>: too many connections, turning #12 away
cmdserv <info>: #12 closing
cmdserv <info>: #13 connected from [::1]:20026
cmdserv <warning>: too many connections, turning #13 away
cmdserv <info>: #13 closing
cmdserv <info>: #8 client disconnect
cmdserv <info>: #8 closing
cmdserv <info>: #9 client disconnect
cmdserv <info>: #9 closing
cmdserv <info>: #10 client disconnect
cmdserv <info>: #10 closing
cmdserv <info>: #11 client disconnect
cmdserv <info>: #11 closing
-- TESTCASE 3 --
cmdserv <info>: #14 connected from [::1]:30001
cmdserv <info>: server shutdown initialized
cmdserv <info>: #14 closing
cmdserv <info>: server shutdown reached
